services:
  n8n:
    image: n8nio/n8n:latest-arm64
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=instructedly-unstultifying-irving.ngrok-free.dev
      - N8N_PROTOCOL=https
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - TZ=Asia/Kolkata
    volumes:
      - ~/.n8n:/home/node/.n8n

